first hw
KozlovAlexandr/technosphere_cpp pull request #1
Opened 2020-10-06 21:27 UTC by KozlovAlexandr

2020-10-08 16:01 UTC, a-badin requested changes
Очень неплохо!

2020-10-08 16:01 UTC, a-badin commented on CMakeLists.txt
> +project(Process)
обычно project идет сразу после cmake_minimum_required

2020-10-08 16:01 UTC, a-badin commented on lib/processor/include/process.h
> +}
Обычно пишут } // namespace process

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +    if (pipe2(pipes[0], O_CLOEXEC) < 0 || pipe2(pipes[1], O_CLOEXEC) < 0)
Если один из pipe2 сработает, а другой нет, вы не будете который успешно отработал, так как вам его придется закрыть

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +    int pipes[2][2];
лучше дать человеческие имена

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +        throw std::runtime_error(strerror(errno));
открытые дескрипторы нужно закрыть

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +    if (!pid)
лучше явное pid == 0

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +        if (dup2(pipes[0][1], 1) < 0 ||  dup2(pipes[1][0], 0) < 0)
STDIN_FILENO вместо цифр

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +                throw std::runtime_error(strerror(errno));
опять нужно закрыть открытые пайпы

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +        execvp(path.data(), const_cast<char *const *>(argsToPass.data()));
не очень хорошо кастить const к non-const, вам очень дешево обойдется сделать копию args и сформировать std::vector<char*> из него, лучше в отдельной функции

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +        if (dup2(pipes[0][1], 1) < 0 ||  dup2(pipes[1][0], 0) < 0)
после dup2 нужно закрыть все pipes

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +    fdRead_ = fdWrite_= -1;
лучше на каждой строчке

2020-10-08 16:01 UTC, a-badin commented on lib/processor/src/process.cpp
> +        argsToPass.reserve(args.size() + 2);
а почему +2

2020-10-08 16:01 UTC, a-badin commented on CMakeLists.txt
> +add_subdirectory(lib)
Давайте добавим какую-нибудь тестовую программку

2020-10-08 16:31 UTC, KozlovAlexandr commented on lib/processor/src/process.cpp
> +        argsToPass.reserve(args.size() + 2);
Сам path и nullptr

2020-10-08 16:36 UTC, KozlovAlexandr commented on lib/processor/src/process.cpp
> +        if (dup2(pipes[0][1], 1) < 0 ||  dup2(pipes[1][0], 0) < 0)
Вы имеете в виду в случае неуспешного выполнения системного вызова? Они ведь закрываются при execvp тк созданы с нужными флагами.

2020-10-13 11:59 UTC, a-badin approved these changes
Поправьте функцию как static и сливайте в главную ветку.
Засчитываю на 10 баллов

2020-10-13 11:59 UTC, a-badin commented on lib/processor/src/process.cpp
> +std::vector<char*> Process::makeArgsToPass(std::string &path, std::vector<std::string>& args)
Так как эта функция приватная и не использует никакие члены класса, скорее всего её лучше сделать просто глобальной функцией. Это скроет детали реализации, чем эта функция и является и уменьшит размер класса. Не забудьте объявить ее как static или в анонимном пространстве имен.

2020-10-13 13:46 UTC, KozlovAlexandr commented on lib/processor/src/process.cpp
> +std::vector<char*> Process::makeArgsToPass(std::string &path, std::vector<std::string>& args)
а как это уменьшит размер класса?

2020-10-14 20:23 UTC, merged