Hw 4
KozlovAlexandr/technosphere_cpp pull request #4
Opened 2020-10-30 14:46 UTC by KozlovAlexandr

2020-11-12 18:35 UTC, Kapitonov requested changes

2020-11-12 18:35 UTC, Kapitonov commented on lib/shmem/include/shared_map.h
> +        state->blocks_count = blockCount - std::floor(header_size);
А точно floor?

2020-11-12 18:35 UTC, Kapitonov commented on lib/shmem/include/shared_map.h
> +        map_->erase(transformKey(key));
А где возвращаемое значение? Или надо убрать его у сигнатуры.

2020-11-12 18:35 UTC, Kapitonov commented on lib/shmem/include/shared_map.h
> +class SharedMap
А как мы освобождаем общую память?

2020-11-17 19:57 UTC, KozlovAlexandr commented on lib/shmem/include/shared_map.h
> +class SharedMap
в деструкторе unique_ptr

2020-11-23 07:42 UTC, Kapitonov requested changes

2020-11-23 07:42 UTC, Kapitonov commented on lib/shmem/include/shared_map.h
> +        map_ = pMap(new (ShAlloc<Map>{state}.allocate(1)) Map(ShAlloc<PairAllocator>{state}),
Я правильно понимаю, что мы вызовем деструктор у мапы, в деструкторе SharedMap? Мы уничтодили мапу в процессе, кторый раньше всех закончил, а остальные процессы как теперь работать должны, если мапа уничтожена?

2020-11-23 15:21 UTC, KozlovAlexandr commented on lib/shmem/include/shared_map.h
> +        map_ = pMap(new (ShAlloc<Map>{state}.allocate(1)) Map(ShAlloc<PairAllocator>{state}),
исправил

2020-11-24 08:17 UTC, Kapitonov requested changes

2020-11-24 08:17 UTC, Kapitonov commented on lib/shmem/include/shared_map.h
> +        semaphore_ = pSemaphore(new (ShAlloc<Semaphore>{state}.allocate(1)) Semaphore{},
А мы точно хотим выделять под семафор и мапу по отельному блоку памяти? Насколько я знаю, это довольно маленькие структуры.

2020-11-25 07:51 UTC, Kapitonov requested changes

2020-11-25 07:51 UTC, Kapitonov commented on lib/shmem/include/shared_map.h
> +                                [](Semaphore *semaphore) { semaphore->~Semaphore(); });
Кажется, что семафор не надо удалять в деструкторе, он используется несколькими процессами.

2020-11-25 07:51 UTC, Kapitonov commented on lib/shmem/include/shared_map.h
> +class SharedMap
Не вижу метода удаления SharedMap. Посколку у неё есть ресурсы, которые надо освободить, то кажется логичным, что последний пользовательдолжен освободить их. Скорее всего, это родительский поток.

2020-11-26 11:25 UTC, merged