Hw 6
KozlovAlexandr/technosphere_cpp pull request #6
Opened 2020-11-20 19:53 UTC by KozlovAlexandr

race condition, epoll_wait срабатывает дважды на EPOLLOUT

2020-11-25 10:35 UTC, Kapitonov requested changes

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/example/http_client.cpp
> +//
Цель http_client не соберется, поскольку нет функции main.

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http.cpp
> +    std::string HttpRequest::toString()
Напрашивается const.

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http.cpp
> +            result.append(header)
А через += не будет компактнее, да и далее именно его вы и используете?

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http.cpp
> +    std::string HttpMessage::headersAndBodyToString()
С виду это константный метод.

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http.cpp
> +        lineStream >> uri_;
Что будет если uri_ пусто?

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/include/http.h
> +    int statusCode;
Забыли постфикс _.

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/include/http.h
> +    std::unordered_map<std::string, std::string> headers_;
А зачем нам публличность данных полей?

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/example/http_server.cpp
> +    response.statusCode = 200;
Если публичность данных полей нужна только тут, то почему бы их не распарсить из строки?

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http_server.cpp
> +        for (int i = 0; i < std::min(std::thread::hardware_concurrency(), threadsNum); ++i)
На самом деле это не всегда оптимальное ограничение сверху. У вас может быть сложная логика обработки запроса, в процессе которой может быть долгое ожидание ответа от другого сервиса, что породит простой железа. На данный, момент можно оставить так.

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http.cpp
> +    std::string HttpResponse::toString()
const

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http.cpp
> +        if (line.empty() || line.back() != '\r')
Предлагаю вынести это в отдельную функцию, напрмер readRequestLine(std::istringstream&)

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/src/http.cpp
> +        if (line.back() != '\r')
Предлагаю вынести это в отдельную функцию, напрмер readStatusLine(std::istringstream&)

2020-11-25 10:35 UTC, Kapitonov commented on lib/http/example/http_server.cpp
> +    conn.addEvent(EPOLLOUT);
Не уверен, что пользователю надо самому управлять флагами, предлагаю обернуть все 3 вызова в одну функцию без параметров.

2020-11-25 22:09 UTC, KozlovAlexandr commented on lib/http/src/http.cpp
> +        lineStream >> uri_;
в http оно не может быть пустым, значит мы примем версию за uri

2020-12-06 21:54 UTC, Kapitonov requested changes
В иделае хочется видеть тесты на парсеры запросов.

2020-12-06 21:54 UTC, Kapitonov commented on lib/http/src/http_server.cpp
> +void HttpServer::run(unsigned threadsNum)
А что мы делаем с соединениями со статусом keep-alive? Сейчас они живут вечно, по идее должен быть таймаут после которрого мы их закроем.

2020-12-12 10:56 UTC, merged